name: deploy_staging
on:
    push: 
        branches:
            - staging
jobs:
    build:
        name: Deploy to staging
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP
              uses:  shivammathur/setup-php@v2
              with:
                php-version: '8.2'
            
            - name: Setup Node JS
              uses: actions/setup-node@v3
              with:
                node-version: 18.x

            - name: Build Assets
              run: |
                composer install -n --prefer-dist
                npm run staging

            - uses: shallwefootball/s3-upload-action@master
              name: Upload S3
              id: S3
              with:
                aws_key_id: ${{ secrets.AWS_KEY_ID }}
                aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
                aws_bucket: ${{ secrets.AWS_BUCKET }}
                source_dir: 'build_staging'