name: deploy_production
on:
    push: 
        branches:
            - production
jobs:
    build:
        name: Deploy to Production
        runs-on: ubuntu-latest
        environment: Production
        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP
              uses:  shivammathur/setup-php@v2
              with:
                php-version: '8.2'
            
            - name: Setup Node JS
              uses: actions/setup-node@v3
              with:
                node-version: 18.x

            - name: Build Assets
              run: |
                composer install -n --prefer-dist
                npm ci
                npm run prod
                npm install html-minifier -g
                html-minifier --conservative-collapse --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css false --minify-js false --file-ext html --input-dir=build_production --output-dir=build_production
                export AWS_ACCESS_KEY_ID=${{ secrets.AWS_KEY_ID }}
                export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY}}
                ls ./build_production
                aws s3 cp ./build_production s3://${{ secrets.AWS_BUCKET }} --recursive --region us-east-1
                aws cloudfront create-invalidation --region us-east-1 --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"