name: deploy_staging
on:
    push: 
        branches:
            - staging
jobs:
    build:
        name: Deploy to staging
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP
              uses:  shivammathur/setup-php@v2
              with:
                php-version: '8.2'
            
            - name: Setup Node JS
              uses: actions/setup-node@v3
              with:
                node-version: 18.x

            - name: Build Assets
              run: |
                composer install -n --prefer-dist
                npm ci
                npm run staging
                export AWS_ACCESS_KEY_ID=${{ secrets.AWS_KEY_ID }}
                export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY}}
                aws s3 cp ./build_staging/* s3://${{ secrets.AWS_BUCKET }} --recursive --acl public-read